import {
    ensureMarkdownExtension,
    extractHeading,
    generateFilename,
    generateUniqueName,
    getExtension,
    isAutoGeneratedName,
    removeExtension,
    sanitizeFilename,
    validateFilename
} from '@/utils/filename';
import { describe, expect, it } from 'vitest';

describe('extractHeading', () => {
    it('should extract H1 heading', () => {
        const result = extractHeading('# My Document');

        expect(result).toBe('My Document');
    });

    it('should extract first H1 from multiple headings', () => {
        const result = extractHeading('# First\n## Second\n# Third');

        expect(result).toBe('First');
    });

    it('should return null for no heading', () => {
        const result = extractHeading('No heading here');

        expect(result).toBeNull();
    });

    it('should clean markdown characters from heading', () => {
        const result = extractHeading('# **Bold** and *italic*');

        expect(result).toBe('Bold and italic');
    });

    it('should return null for empty content', () => {
        expect(extractHeading('')).toBeNull();
    });

    it('should handle H1 with only whitespace after #', () => {
        expect(extractHeading('#    Spaced Title   ')).toBe('Spaced Title');
    });
});

describe('sanitizeFilename', () => {
    it('should remove invalid characters', () => {
        const result = sanitizeFilename('file:name?test');

        expect(result).toBe('filenametest');
    });

    it('should normalize whitespace', () => {
        const result = sanitizeFilename('file   name');

        expect(result).toBe('file name');
    });

    it('should trim whitespace', () => {
        const result = sanitizeFilename('  filename  ');

        expect(result).toBe('filename');
    });

    it('should limit length to 50 characters', () => {
        const longName = 'a'.repeat(150);
        const result = sanitizeFilename(longName);

        expect(result.length).toBe(50);
    });

    it('should return Untitled for empty string', () => {
        expect(sanitizeFilename('')).toBe('Untitled');
    });

    it('should return Untitled for only invalid chars', () => {
        expect(sanitizeFilename('???***')).toBe('Untitled');
    });

    it('should truncate at word boundary when possible', () => {
        const longName = 'This is a very long filename that exceeds the maximum allowed length';
        const result = sanitizeFilename(longName);

        expect(result.length).toBeLessThanOrEqual(50);
        expect(result).not.toMatch(/\s$/); // Should not end with space
    });

    it('should remove markdown formatting characters', () => {
        expect(sanitizeFilename('**bold** and _italic_')).toBe('bold and italic');
    });
});

describe('generateFilename', () => {
    it('should use H1 heading when available', () => {
        const result = generateFilename('# My Document\n\nSome content');

        expect(result).toBe('My Document');
    });

    it('should use first non-empty line when no heading', () => {
        const result = generateFilename('First line\nSecond line');

        expect(result).toBe('First line');
    });

    it('should skip frontmatter delimiter', () => {
        const result = generateFilename('---\ntitle: Test\n---\nContent here');

        // Note: colon is removed by sanitizeFilename
        expect(result).toBe('title Test');
    });

    it('should return default name for empty content', () => {
        expect(generateFilename('')).toBe('Untitled');
    });

    it('should use custom default name', () => {
        expect(generateFilename('', 'Custom Default')).toBe('Custom Default');
    });

    it('should skip empty lines', () => {
        const result = generateFilename('\n\n\nActual content');

        expect(result).toBe('Actual content');
    });
});

describe('validateFilename', () => {
    it('should return valid for normal name', () => {
        const result = validateFilename('My Document');

        expect(result.valid).toBe(true);
        expect(result.error).toBeUndefined();
    });

    it('should return invalid for empty name', () => {
        const result = validateFilename('');

        expect(result.valid).toBe(false);
        expect(result.error).toBe('Name cannot be empty');
    });

    it('should return invalid for whitespace only', () => {
        const result = validateFilename('   ');

        expect(result.valid).toBe(false);
        expect(result.error).toBe('Name cannot be empty');
    });

    it('should return invalid for name too long', () => {
        const result = validateFilename('a'.repeat(60));

        expect(result.valid).toBe(false);
        expect(result.error).toContain('too long');
    });

    it('should return invalid for invalid characters', () => {
        const result = validateFilename('file?name');

        expect(result.valid).toBe(false);
        expect(result.error).toContain('invalid characters');
    });

    it('should accept names with spaces', () => {
        expect(validateFilename('My Document Name').valid).toBe(true);
    });

    it('should accept names with numbers', () => {
        expect(validateFilename('Document 123').valid).toBe(true);
    });
});

describe('isAutoGeneratedName', () => {
    it('should return true for Untitled', () => {
        expect(isAutoGeneratedName('Untitled')).toBe(true);
    });

    it('should return true for Untitled with number', () => {
        expect(isAutoGeneratedName('Untitled 1')).toBe(true);
        expect(isAutoGeneratedName('Untitled 99')).toBe(true);
    });

    it('should return false for custom names', () => {
        expect(isAutoGeneratedName('My Document')).toBe(false);
    });

    it('should return false for names containing Untitled but not starting with it', () => {
        expect(isAutoGeneratedName('Not Untitled')).toBe(false);
    });
});

describe('generateUniqueName', () => {
    it('should return base name if not in existing names', () => {
        const result = generateUniqueName('Document', ['Other']);

        expect(result).toBe('Document');
    });

    it('should append number if name exists', () => {
        const result = generateUniqueName('Document', ['Document']);

        expect(result).toBe('Document 1');
    });

    it('should find next available number', () => {
        const result = generateUniqueName('Document', ['Document', 'Document 1', 'Document 2']);

        expect(result).toBe('Document 3');
    });

    it('should handle empty existing names', () => {
        const result = generateUniqueName('Document', []);

        expect(result).toBe('Document');
    });
});

describe('getExtension', () => {
    it('should return file extension', () => {
        expect(getExtension('file.md')).toBe('md');
    });

    it('should return lowercase extension', () => {
        expect(getExtension('file.MD')).toBe('md');
    });

    it('should return empty string for no extension', () => {
        expect(getExtension('filename')).toBe('');
    });

    it('should handle multiple dots', () => {
        expect(getExtension('file.name.md')).toBe('md');
    });

    it('should handle hidden files', () => {
        expect(getExtension('.gitignore')).toBe('gitignore');
    });
});

describe('removeExtension', () => {
    it('should remove file extension', () => {
        expect(removeExtension('file.md')).toBe('file');
    });

    it('should return unchanged if no extension', () => {
        expect(removeExtension('filename')).toBe('filename');
    });

    it('should handle multiple dots', () => {
        expect(removeExtension('file.name.md')).toBe('file.name');
    });

    it('should handle hidden files', () => {
        expect(removeExtension('.gitignore')).toBe('');
    });
});

describe('ensureMarkdownExtension', () => {
    it('should add .md extension if missing', () => {
        expect(ensureMarkdownExtension('document')).toBe('document.md');
    });

    it('should keep .md extension', () => {
        expect(ensureMarkdownExtension('document.md')).toBe('document.md');
    });

    it('should keep .markdown extension', () => {
        expect(ensureMarkdownExtension('document.markdown')).toBe('document.markdown');
    });

    it('should replace other extensions with .md', () => {
        expect(ensureMarkdownExtension('document.txt')).toBe('document.md');
    });

    it('should handle files with multiple dots', () => {
        expect(ensureMarkdownExtension('my.document.txt')).toBe('my.document.md');
    });
});
